--USE [master]
--GO
--/****** Object:  Database [PickleAndHope]    Script Date: 5/2/2020 10:50:56 AM ******/
--CREATE DATABASE [PickleAndHope]
-- CONTAINMENT = NONE
-- ON  PRIMARY 
--( NAME = N'PickleAndHope', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\PickleAndHope.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
-- LOG ON 
--( NAME = N'PickleAndHope_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\PickleAndHope_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
--GO
--ALTER DATABASE [PickleAndHope] SET COMPATIBILITY_LEVEL = 140
--GO
--IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
--begin
--EXEC [PickleAndHope].[dbo].[sp_fulltext_database] @action = 'enable'
--end
--GO
--ALTER DATABASE [PickleAndHope] SET ANSI_NULL_DEFAULT OFF 
--GO
--ALTER DATABASE [PickleAndHope] SET ANSI_NULLS OFF 
--GO
--ALTER DATABASE [PickleAndHope] SET ANSI_PADDING OFF 
--GO
--ALTER DATABASE [PickleAndHope] SET ANSI_WARNINGS OFF 
--GO
--ALTER DATABASE [PickleAndHope] SET ARITHABORT OFF 
--GO
--ALTER DATABASE [PickleAndHope] SET AUTO_CLOSE OFF 
--GO
--ALTER DATABASE [PickleAndHope] SET AUTO_SHRINK OFF 
--GO
--ALTER DATABASE [PickleAndHope] SET AUTO_UPDATE_STATISTICS ON 
--GO
--ALTER DATABASE [PickleAndHope] SET CURSOR_CLOSE_ON_COMMIT OFF 
--GO
--ALTER DATABASE [PickleAndHope] SET CURSOR_DEFAULT  GLOBAL 
--GO
--ALTER DATABASE [PickleAndHope] SET CONCAT_NULL_YIELDS_NULL OFF 
--GO
--ALTER DATABASE [PickleAndHope] SET NUMERIC_ROUNDABORT OFF 
--GO
--ALTER DATABASE [PickleAndHope] SET QUOTED_IDENTIFIER OFF 
--GO
--ALTER DATABASE [PickleAndHope] SET RECURSIVE_TRIGGERS OFF 
--GO
--ALTER DATABASE [PickleAndHope] SET  DISABLE_BROKER 
--GO
--ALTER DATABASE [PickleAndHope] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
--GO
--ALTER DATABASE [PickleAndHope] SET DATE_CORRELATION_OPTIMIZATION OFF 
--GO
--ALTER DATABASE [PickleAndHope] SET TRUSTWORTHY OFF 
--GO
--ALTER DATABASE [PickleAndHope] SET ALLOW_SNAPSHOT_ISOLATION OFF 
--GO
--ALTER DATABASE [PickleAndHope] SET PARAMETERIZATION SIMPLE 
--GO
--ALTER DATABASE [PickleAndHope] SET READ_COMMITTED_SNAPSHOT OFF 
--GO
--ALTER DATABASE [PickleAndHope] SET HONOR_BROKER_PRIORITY OFF 
--GO
--ALTER DATABASE [PickleAndHope] SET RECOVERY FULL 
--GO
--ALTER DATABASE [PickleAndHope] SET  MULTI_USER 
--GO
--ALTER DATABASE [PickleAndHope] SET PAGE_VERIFY CHECKSUM  
--GO
--ALTER DATABASE [PickleAndHope] SET DB_CHAINING OFF 
--GO
--ALTER DATABASE [PickleAndHope] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
--GO
--ALTER DATABASE [PickleAndHope] SET TARGET_RECOVERY_TIME = 60 SECONDS 
--GO
--ALTER DATABASE [PickleAndHope] SET DELAYED_DURABILITY = DISABLED 
--GO
--EXEC sys.sp_db_vardecimal_storage_format N'PickleAndHope', N'ON'
--GO
--ALTER DATABASE [PickleAndHope] SET QUERY_STORE = OFF
--GO
USE [PickleAndHope]
GO
/****** Object:  Table [dbo].[Pickle]    Script Date: 5/2/2020 10:50:56 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Pickle](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Type] [varchar](100) NOT NULL,
	[NumberInStock] [int] NOT NULL,
	[Price] [decimal](18, 0) NOT NULL,
	[Size] [varchar](20) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [PickleAndHope] SET  READ_WRITE 
GO